services:
  frontend:
    build: './frontend'
    container_name: '200lab-lab2-frontend'
    ports:
      - "3000:3000"
    networks:
      - lab-net

  db:
    platform: linux/amd64
    image: mysql:5.7
    container_name: '200lab-lab2-db'
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=labdb
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - lab-net


  backend:
    build: './backend'
    container_name: '200lab-lab2-backend'
    ports:
      - "5001:5001"
    volumes:
      - ./backend:/app
    environment:
      - FLASK_ENV=development
    depends_on:
      - db
    networks:
      - lab-net

  nginx:
    image: nginx:alpine
    container_name: '200lab-lab2-nginx'
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
    networks:
      - lab-net

volumes:
  db-data:

networks:
  lab-net:
    driver: bridge